version: '3.3'
services:

  db:
    image: postgres:12.9-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123qwe!E!E"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: litops/foodgram:v1
    restart: always
    volumes:
      - static_value:/app/static_web/
      - media_value:/app/media_web/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: litops/foodgram_front:v1
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - web
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_web/
      - media_value:/var/html/media_web/
    depends_on:
      - frontend
      - web
volumes:
  static_value:
  media_value:
  postgres_data:
