# Generated by Django 2.2.16 on 2022-02-02 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220201_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='tag_color'),
        ),
    ]
