# Generated by Django 2.2.16 on 2022-01-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220122_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='omg', to='app.Tag', verbose_name='recipe_tag'),
        ),
    ]
