# Generated by Django 2.2.16 on 2022-01-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220123_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='app.Tag', verbose_name='recipe_tag'),
        ),
    ]
