# Generated by Django 2.2.16 on 2022-01-23 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20220123_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientforrecipe',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_recipe', to='app.Ingredient', verbose_name='name_ingredient_for_recipe'),
        ),
    ]
