# Generated by Django 2.2.16 on 2022-01-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220124_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='code',
            field=models.CharField(max_length=30, unique=True, verbose_name='tag_colour'),
        ),
    ]
